# Form implementation generated from reading ui file '.\ui\edit_reservation_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 553)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.room_number_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_number_label.setFont(font)
        self.room_number_label.setObjectName("room_number_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.room_number_label)
        self.room_number_box = QtWidgets.QComboBox(parent=Dialog)
        self.room_number_box.setObjectName("room_number_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.room_number_box)
        self.room_type_box = QtWidgets.QComboBox(parent=Dialog)
        self.room_type_box.setObjectName("room_type_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.room_type_box)
        self.room_type_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_type_label.setFont(font)
        self.room_type_label.setObjectName("room_type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.room_type_label)
        self.room_status_box = QtWidgets.QComboBox(parent=Dialog)
        self.room_status_box.setObjectName("room_status_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.room_status_box)
        self.room_status_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_status_label.setFont(font)
        self.room_status_label.setObjectName("room_status_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.room_status_label)
        self.client_box = QtWidgets.QComboBox(parent=Dialog)
        self.client_box.setObjectName("client_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.client_box)
        self.client_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_label.setFont(font)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.client_label)
        self.check_in_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_in_label.setFont(font)
        self.check_in_label.setObjectName("check_in_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.check_in_label)
        self.check_in_date_edit = QtWidgets.QDateEdit(parent=Dialog)
        self.check_in_date_edit.setObjectName("check_in_date_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.check_in_date_edit)
        self.check_out_date_edit = QtWidgets.QDateEdit(parent=Dialog)
        self.check_out_date_edit.setObjectName("check_out_date_edit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.check_out_date_edit)
        self.check_out_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_out_label.setFont(font)
        self.check_out_label.setObjectName("check_out_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.check_out_label)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменение размещения"))
        self.room_number_label.setText(_translate("Dialog", "Номер комнаты:"))
        self.room_type_label.setText(_translate("Dialog", "Тип комнаты:"))
        self.room_status_label.setText(_translate("Dialog", "Статус:"))
        self.client_label.setText(_translate("Dialog", "Клиент:"))
        self.check_in_label.setText(_translate("Dialog", "Дата въезда:"))
        self.check_out_label.setText(_translate("Dialog", "Дата выезда:"))
        self.pushButton.setText(_translate("Dialog", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
